apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: log-body
  annotations:
    sidecar.istio.io/logLevel: info
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        # context omitted so that this applies to both sidecars and gateways
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value: # lua filter specification
          name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            always_set_request_id_in_response: true
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: kmamiz-wasm-envoyfilter
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://{YOUR_REGISTRY}/kmamiz-wasm-envoyfilter:latest
  phase: AUTHN
