apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: log-body
  annotations:
    sidecar.istio.io/logLevel: info
spec:
  configPatches:
    # The second patch instructs to apply the above Wasm filter to the listener/http connection manager.
    - applyTo: HTTP_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: kmamiz-wasm-filter # This must match the name above
          config_discovery:
            config_source:
              ads: {}
            type_urls:
              ["type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm"]
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: kmamiz-wasm
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://{YOUR_REGISTRY}/kmamiz-wasm:latest
  phase: AUTHN
