apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmamiz
  namespace: kmamiz-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kmamiz
    spec:
      containers:
        - name: kmamiz
          image: "{your-image}"
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGODB_URI
              value: "{your-mongodb-uri}"
            - name: ZIPKIN_URL
              value: "http://zipkin.istio-system:9411"
            - name: LOG_LEVEL
              value: "info"
            - name: IS_RUNNING_IN_K8S
              value: "true"
            - name: ENVOY_LOG_LEVEL
              value: "warning" # accept: info | warning | error
            - name: READ_ONLY_MODE
              value: "false"
            - name: ENABLE_TESTING_ENDPOINTS
              value: "false"
  selector:
    matchLabels:
      app: kmamiz
---
apiVersion: v1
kind: Service
metadata:
  name: kmamiz
  namespace: kmamiz-system
spec:
  type: NodePort
  selector:
    app: kmamiz
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
